
### CLIENTES ###
###

GET http://localhost:3000/api/clientes

###

POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "nombre": "Pepe",
  "apellidos": "Viyuela",
  "direccion": "c olvido 10",
  "telefono": 666666666,
  "fecha_nacimiento": "1980-03-10",
  "dni": "99999999x",
  "email": "pepeviyuela@gmail.com"
}

###

PUT  http://localhost:3000/api/clientes/3
Content-Type: application/json

{
    "nombre": "pepe",
    "apellidos": "rus",
    "direccion": "adios",
    "telefono": "999999999",
    "fecha_nacimiento": "1980-03-10",
    "dni": "12345678e",
    "email": "domi@gmail.com"
}

###


DELETE  http://localhost:3000/api/clientes/6


### HOTELES ###
###

GET http://localhost:3000/api/hoteles


###

POST http://localhost:3000/api/hoteles
Content-Type: application/json

{
   "nombre": "Pequeñajo",
    "direccion": "perdida,2",
    "ciudad": "Jaen",
    "num_estrellas": 3,
    "descripcion": "Regulero",
    "tarifa": 50
}

###

PUT  http://localhost:3000/api/hoteles/3
Content-Type: application/json

{
   "nombre": "Pequeñajo",
    "direccion": "perdida,2",
    "ciudad": "Jaen",
    "num_estrellas": 3,
    "descripcion": "Regulero lagarto",
    "tarifa": 50
}

###

DELETE  http://localhost:3000/api/hoteles/3

###




